spring:
  profiles:
    active: prod

server:
  servlet:
    context-path: /
  port: 8080

google:
  directions:
    key: AIzaSyB1kvAJG6g3PHdlgjk7fl8tLl1YZL1p7Ww
    url: https://maps.googleapis.com/maps/api/directions/json